language: node_js
dist: focal

notifications:
  email: false

install:
  - npm install

cache: false

jobs:
  include:
    - name: "CI"
      script:
      - npm run test:all
      - npm run stylelint
      - npm run lint
    - if: branch =~ /^(master|next)$/
      stage: "deploy"
      script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - npm run release:publish
      skip_cleanup: true
