language: node_js
dist: focal

notifications:
  email: false

install:
  - npm ci

jobs:
  include:
    - name: "Unit Tests"
      script: npm run test:all
    # - name: "Audit"
    #   script: npm audit || echo \"audit found some vulnerabilities.\"
    - name: "Lint"
      script: npm run lint
    - if: branch =~ /^(master|next)$/
      stage: "deploy"
      script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - npm run release:publish
      skip_cleanup: true
